"""add created_at to information

Revision ID: ef3f1a358b3f
Revises: 
Create Date: 2026-10-04 10:50:39.988563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3f1a358b3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False)) # server_default=sa.func.now(): Khi thêm column này mà cần một giá trị mặc định, dùng thời gian hiện tại của database. Nhờ vậy historical rows không bị NULL
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
